### ISSUE TITLE
Performance and design issues

### ISSUE THREAD

**Issue by ivan-cukic** [mhogomchungu/tasks#2]
Hi,

This _issue_ is, in essence, a reply to your comment on http://cukic.co/2016/01/17/asynqt-framework-making-qfuture-useful/

> @mnogo mchungu
>
> I've seen the library (on reddit). It is interesting, especially the future class design, 
> but I have a few issues with it. I'll reply on github. :)
>
> For this library, I needed to use QFutures (would not be my first choice) and not roll out my own, 
> because I already have a QFuture-based library in which I want to use this code.

While the title of the _issue_ sounds overly serious, there are a few potential problems 
I see with the current version of your library.

- spinning new threads is not cheap (and new event loops). So, the await will actually be quite expensive. Now, until we get the proper await in C++17, this is one of the valid solutions for this problem. I'd advise you to also check boost.coroutine, maybe you'll get ideas how to improve this without relying on Qt's event loop. (another thing - I haven't checked the QEventLoop implementation - what happens to the events that are already scheduled for processing in the current event loop when one of the events invokes await?)

- wrapping stuff in std::function is also not cheap. From what I've seen in the API, you would be able to avoid using std::function for the most part, and receive functions as template arguments (something like `tasks::future_impl<T, StartFunction, CancelFunction, GetFunction>`), and only if the user actually wants to save the future in a variable that can not be declared as `auto`, perform the type-erasure and create tasks::future<T>. Though, on the other hand, this would make the code much more difficult to maintain.

The idea is really nice, and would be awesome to have a library like this for C++/Qt. (maybe some things should be in Qt like .then, but I don't expect we will see many improvements to QFuture unfortunately)

Cheers,
Ivan

p.s. I hope I didn't sound offputting - I sometimes do unwantingly sound negative, but I'm really not :)

**Comment by mhogomchungu** [comment]
no,you didnt sound "offputting" at all :-)

C++ is all about performance and i already though of the things you said and i have made numerous attempts at looking into how QEventLoop is implemented in an attempt to see how "expensive" my .await() is. My .await() looks slow but its good enough with non blocking GUI programming where my simple is primarily meant to be used.

I have also been paying close attention into various discussions about how expensive std::function so i am not unaware of its price but for GUI programming,the functionality and easy of use of the library seems to out weight the the price.

I started with using thread pools as provided by Qt but decided against them since using thread pools involves active management of the pool. To use it,questions like should the default global thread pool be used or a private one? If a private one,then how many threads should be in the thread pool,if user starts 3 tasks while the thread pool has only one thread available,should the tasks be queued or "external" threads be used or the thread pool be increased. Thread pools are a mess for a simple library.

My understanding says Qthreads are not as expensive as you make them to be because Qthread does not spin up new threads each and every time users use QThread as existing threads are reuses and my simple test below proves this assumption of mine.

Below code:

```

static void _printThreadID()
{
	std::cout << "---------------------"    << std::endl ;
	std::cout << QThread::currentThreadId() << std::endl;
	std::cout << std::this_thread::get_id() << std::endl;
	std::cout << pthread_self() << std::endl;
	std::cout << "---------------------"    << std::endl ;
}
void test()
{
	Task::run( [](){
		_printThreadID();
		sleep( 3 ) ;
	} ).await() ;
}

void example::run()
{
	test() ;
	test() ;
	test() ;
	test() ;
	test() ;
	test() ;
	test() ;

```

produces this output

```
---------------------
140215724570368
140215724570368
140215724570368
---------------------
---------------------
140215724570368
140215724570368
140215724570368
---------------------
---------------------
140215724570368
140215724570368
140215724570368
---------------------
---------------------
140215716177664
140215716177664
140215716177664
---------------------
---------------------
140215724570368
140215724570368
140215724570368
---------------------
---------------------
140215716177664
140215716177664
140215716177664
---------------------
---------------------
140215724570368
140215724570368
140215724570368
---------------------

```
and this shows that 7 different instances of QThread reused 2 different threads.

**Comment by ivan-cukic** [comment]
Yes, Qt fortunately reuses threads. The context switching remains as the 'slow' part.

Though, you are right, for GUI applications it does not really matter. I'm just in a over-optimizing frame of mind right now. Maybe that is the reason behind the fact that more than a few projects of mine never saw the light of the day. :)
